CurrentXpose/Controllers/EconomiaController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CurrentXpose.Controllers
{
    [Authorize]
    public class EconomiaController : Controller
    {
        public IActionResult Economia()
        {
            return View();
        }
        public IActionResult EconomiaSindico()
        {
            return View();
        }
    }
}

CurrentXpose/Controllers/FaleConoscoController.cs
using CurrentXpose.Domain.Entidades;
using CurrentXpose.Domain.Interface;
using CurrentXpose.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CurrentXpose.Controllers
{
    [Authorize]
    public class FaleConoscoController : Controller
    {
        private readonly IEmailService _emailService;

        public FaleConoscoController(IEmailService emailService)
        {
            _emailService = emailService;
        }
        public IActionResult FaleConosco()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> FaleConosco(FaleConosco model)
        {
            if (ModelState.IsValid)
            {
                await _emailService.EnviarMensagemFaleConosco(model);

                return RedirectToAction("Sucesso");
            }
            return View(model);
        }

        public IActionResult Sucesso()
        {
            return View();
        }
    }
}

CurrentXpose/Controllers/LoginController.cs
using CurrentXpose.ApiService.Interfaces;
using CurrentXpose.Domain.Entidades;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Newtonsoft.Json;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;

namespace CurrentXpose.Controllers
{
    public class LoginController : Controller
    {
        public readonly IAuthApiService _authApiService;
        private readonly ILogger<LoginController> _logger;

        public LoginController(IAuthApiService authApiService, ILogger<LoginController> logger)
        {
            _authApiService = authApiService;
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Login(string username, string senha)
        {
            var resultMorador = await _authApiService.Autenticar(username, senha, "morador");
            var resultSindico = await _authApiService.Autenticar(username, senha, "sindico");

            if (resultMorador != null)
            {
                var token = JsonConvert.DeserializeObject<TokenResponse>(resultMorador.ToString());

                if (token != null)
                {
                    TempData["AccessToken"] = token.Token;

                    string tipoUsuario = ObterTipoUsuarioDoToken(token);

                    var claims = new List<Claim>
                        {
                            new Claim(ClaimTypes.Hash, token.Token),
                        };

                    var claimsIdentity = new ClaimsIdentity(
                        claims, CookieAuthenticationDefaults.AuthenticationScheme);

                    var authProperties = new AuthenticationProperties
                    {

                    };

                    await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(claimsIdentity),
                        authProperties);

                    switch (tipoUsuario)
                    {
                        case "Morador":
                            Console.WriteLine("Redirecionando para Inicial");
                            return Redirect("/Morador/Inicial");

                        default:
                            return RedirectToAction("Erro");
                    }
                }
            }

            else if (resultSindico != null)
            {
                var token = JsonConvert.DeserializeObject<TokenResponse>(resultSindico.ToString());

                if (token != null)
                {
                    TempData["AccessToken"] = token.Token;

                    string tipoUsuario = ObterTipoUsuarioDoToken(token);

                    var claims = new List<Claim>
                        {
                            new Claim(ClaimTypes.Hash, token.Token),
                        };

                    var claimsIdentity = new ClaimsIdentity(
                   claims, CookieAuthenticationDefaults.AuthenticationScheme);

                    var authProperties = new AuthenticationProperties
                    {

                    };

                    await HttpContext.SignInAsync(
                        CookieAuthenticationDefaults.AuthenticationScheme,
                        new ClaimsPrincipal(claimsIdentity),
                        authProperties);

                    switch (tipoUsuario)
                    {
                        case "Sindico":
                            Console.WriteLine("Redirecionando para Sindico");
                            return RedirectToAction("Sindico", "Sindico");

                        default:
                            return RedirectToAction("Erro");
                    }
                }
            }

            TempData["Status"] = "Usuário ou senha incorretos";
            return RedirectToAction("Index");
        }

        public IActionResult TrocarSenha()
        {
            return View();
        }

        public IActionResult Logout()
        {
            TempData.Remove("AccessToken");
            HttpContext.SignOutAsync();
            return Redirect("/Login/Index");
        }

        private string ObterTipoUsuarioDoToken(TokenResponse token)
        {
            return token.TipoUsuario;
        }
    }
}

CurrentXpose/Controllers/SobreController.cs
using CurrentXpose.Domain.Entidades;
using CurrentXpose.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CurrentXpose.Controllers
{
    [Authorize]
    public class SobreController : Controller
    {
        public IActionResult Sobre()
        {
            return View();
        }

        public IActionResult SobreSindico()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

CurrentXpose/Views/BarraLateral/Lateral.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <link rel="stylesheet" href="~/css/barra-lateral/lateral.css">
</head>

<body>
    <div class="sidebar" id="mySidebar">
        <div class="close-btn" style="color:#156D2E;" onclick="toggleSidebar()">x</div>
        <img src="~/img/logo/CurrentXpose.jpg" />
        <ul>
            <li><a asp-controller="Morador" asp-action="Inicial">Inicio</a></li>
            <li><a asp-controller="Morador" asp-action="Historico">Historico</a></li>
            <li><a asp-controller="Economia" asp-action="Economia">Como economizar?</a></li>
            <li><a asp-controller="FaleConosco" asp-action="FaleConosco">Fale Conosco</a></li>
            <li><a asp-controller="Sobre" asp-action="Sobre">Sobre</a></li>
        </ul>
        <a class="logout" asp-controller="Login" asp-action="Logout">Logout</a>
    </div>

    <script>
        function toggleSidebar() {
            var sidebar = document.getElementById("mySidebar");
            sidebar.classList.toggle("open");
        }
    </script>
</body>

</html>

CurrentXpose/Views/BarraLateral/LateralSindico.cshtml
<!DOCTYPE html>
<html lang="pt-br">

<head>
    <link rel="stylesheet" href="~/css/barra-lateral/lateral.css">
</head>

<body>
    <div class="sidebar" id="mySidebar">
        <div class="close-btn" style="color:#156D2E;" onclick="toggleSidebar()">x</div>
        <img src="~/img/logo/CurrentXpose.jpg" />
        <ul>
            <li><a asp-controller="Sindico" asp-action="Sindico">Inicio</a></li>
            <li><a asp-controller="Sindico" asp-action="Historico">Histórico</a></li>
            <li><a asp-controller="Economia" asp-action="EconomiaSindico">Como economizar?</a></li>
            <li><a asp-controller="Sobre" asp-action="SobreSindico">Sobre</a></li>
        </ul>
        <a class="logout" asp-controller="Login" asp-action="Logout">Logout</a>
    </div>

    <script>
        function toggleSidebar() {
            var sidebar = document.getElementById("mySidebar");
            sidebar.classList.toggle("open");
        }
    </script>
</body>

</html>