CurrentXpose/Controllers/FaleConoscoController.cs
using CurrentXpose.Domain.Entidades;
using CurrentXpose.Domain.Interface;
using CurrentXpose.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CurrentXpose.Controllers
{
    [Authorize]
    public class FaleConoscoController : Controller
    {
        private readonly IEmailService _emailService;

        public FaleConoscoController(IEmailService emailService)
        {
            _emailService = emailService;
        }
        public IActionResult FaleConosco()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> FaleConosco(FaleConosco model)
        {
            if (ModelState.IsValid)
            {
                await _emailService.EnviarMensagemFaleConosco(model);

                return RedirectToAction("Sucesso");
            }
            return View(model);
        }

        public IActionResult Sucesso()
        {
            return View();
        }
    }
}

CurrentXpose/Controllers/MoradorController.cs
using CurrentXpose.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CurrentXpose.Controllers
{
    [Authorize]
    public class MoradorController : Controller
    {
        public IActionResult Inicial()
        {
            return View();
        }

        [HttpGet]
        public IActionResult Historico(FiltrosViewModel filtros)
        {
            return View(filtros);
        }
    }
}

CurrentXpose/Views/FaleConosco/FaleConosco.cshtml
@model CurrentXpose.Domain.Entidades.FaleConosco

@{
    ViewData["Title"] = "Fale Conosco";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/sistema/faleConosco.css">
    <link rel="stylesheet" href="~/css/lateral.css">
    <title>Fale Com Especialista</title>
</head>
<br />
<br />
<br />
<b><p>Deixe sua mensagem para que um especialista entre em contato, e realizar um orçamento de projetos com sustentabilidade</p></b>
<body class="login-bg">
    <div class="login-container">
        <div class="open-btn" onclick="toggleSidebar()">☰</div>
        @{
            await Html.RenderPartialAsync("~/Views/BarraLateral/Lateral.cshtml");
        }
        <form class="login-form" asp-action="Inicial" asp-controller="Morador" style="margin-bottom: 80px;">
            <h2>Fale com especialista</h2>
            <label for="Nome">Nome:</label>
            <input type="text" asp-for="Nome" id="Nome" required>

            <label for="Assunto">Assunto:</label>
            <input type="text" asp-for="Assunto" id="Assunto" required>

            <label for="Email">Email:</label>
            <input type="email" asp-for="Email" id="Email" required>

            <label for="Mensagem">Mensagem:</label>
            <textarea asp-for="Mensagem" id="Mensagem" rows="5" required></textarea>

            <button type="submit" aria-label="Enviar Mensagem">Enviar mensagem</button>
            <div class="text-center">
                <a class="link" asp-action="Inicial" asp-controller="Morador">Voltar</a>
            </div>
        </form>
    </div>
</body>
</html>

CurrentXpose/Views/FaleConosco/Sucesso.cshtml
@{
    ViewData["Title"] = "Sucesso";
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/css/sistema/sucesso.css">
    <title>Sucesso</title>
</head>
<body>
    <div class="success-container">
        <h1>Sua mensagem foi enviada com sucesso!</h1>
        <p>Agradecemos por entrar em contato. Responderemos assim que possível.</p>
        <a href="/">Página Inicial</a>
    </div>
</body>
</html>